### ISSUE TITLE
review/audit the code and processes in the kube-stack-private example

### ISSUE THREAD

**Issue by ketzacoatl** [fpco/terraform-aws-foundation#160]
This example env has an existing process to deploy/setup the infrastructure. That env should be reviewed and improved.

### Requirements

* Deploy and review the code and processes.
* Document the results of the experience, identify broken steps and map out solutions
* Aim to add new tickets where needed
* Ensure the deploy/setup process is clearly documented as a set of steps an engineer can walk through
* Propose new make targets or gaps with best practices

**Comment by neilmayhew** [comment]
## My observations:

1. The generated ssh key isn't used
    - `~/.ssh/id_rsa.pub` is used in `variables.tf`

2. I don't particularly like polluting my global ssh config with temporary stuff
    - Have to remember to take it out afterwards
    - I may have other hosts in `10.10.0.0/16`
    - I may have other hosts called `bastion`

3. Can put config in local `ssh_config`
    - Add ` -F ssh_config` to `ssh_args` in `ansible.cfg`

4. ssh config improvements
    - Use `ProxyJump` instead of `ProxyCommand`
        + This enables the local `ssh_config` to be used
    - No need to specify `IdentityFile` (if `~/.ssh/id_rsa` continues to be used)

5. Could link `kubespray-aws-inventory.py` instead of copying it

6. Have to set `REGION` before using `kubespray-aws-inventory.py`

7. Those on Nix/NixOS can use `nix-shell` instead of `pip` with `virtualenvwrapper`:

```Nix
{ nixpkgs ? import <nixpkgs> {} }:

with nixpkgs.pkgs;

stdenv.mkDerivation {
    name = "env";
    buildInputs = [
      ansible
      gettext
      terraform
    ];
}
```
