### ISSUE TITLE
elasticsearch module internal elb bug

### ISSUE THREAD

**Issue by giancarlocosta** [fpco/terraform-aws-foundation#162]
`variables.tf` says that for the `internal_alb` variable map, the `arn` has to be set if `internal_alb. deploy_elb` is false. But if `internal_alb.deploy_elb_internal` is true, which it is by default, (and `internal_alb.deploy_elb` is false) then an internal aws_elb is being created:
https://github.com/fpco/terraform-aws-foundation/blob/master/modules/elasticsearch/data-nodes.tf#L142

So why is the arn needed if that internal elb is created by default? Why can' the arn here be set to the arn of that created internal elb? ^^ 
https://github.com/fpco/terraform-aws-foundation/blob/master/modules/elasticsearch/data-nodes.tf#L203

**Comment by lehins** [comment]
@giancarlocosta It's not a bug, it's a feature ;) Crucial part is recognizing that there is ability to use either an Application Load Balance (ALB) or an Elastic (Classic) Load Balancer (ELB)
Let me try to elaborate on this slightly confusing setup.

Elasticsearch requires a Load Balancer for it's HTTP API on port 9200. It's called internal, since it has no authentication or encryption. There is also an optional external API endpoint which is simply a reverse proxy that provides HTTPS and BasicAuth, but that runs on 9201 and isn't particularly relevant for this ticket.
Now, Load Balancer for internal API is required for ELK to operate properly, and that load balancer can be either an __ALB__ or __ELB__. If `deploy_elb` is `false` it means an externally deployed __ALB__ has been setup, for example with a handy https://github.com/fpco/terraform-aws-foundation/tree/master/modules/web-alb module, and all we need to do now is add a listener on port 9200 for it, i.e. `aws_alb_listener.elasticsearch-api`. On the other hand if `deploy_elb` is `true`, which is the default value as you pointed out, an ELB will be deployed which has it's own listener(https://github.com/fpco/terraform-aws-foundation/blob/master/modules/elasticsearch/data-nodes.tf#L149), thus resource `aws_alb_listener.elasticsearch-api` becomes irrelevant.

The reasoning behind this is fairly straightforward, we can reuse an already deployed ALB that we are using for some other service, for example Kibana UI, but only if that ALB is also internal, eg. ELK is running behind a VPN or something. Or, we can simply have an ELB be deployed by default that Logstash and Kibana can use to communicate with Elasticsearch.

**Comment by giancarlocosta** [comment]
@lehins Thanks for the follow up. I'm confused because in the variables and logic, 
 `internal_alb.deploy_elb` is default false and `internal_alb.deploy_elb_internal` is default true, while you are saying that it is the other way around.

**Comment by lehins** [comment]
@giancarlocosta I see now what is the source of your confusion. 
`internal_alb.deploy_elb` and  `internal_alb.deploy_elb_internal` mean something totally different, see their respective documentation:
https://github.com/fpco/terraform-aws-foundation/blob/1f7c5c6f8f13e2f1428c172b5626b2d9583cb9b6/modules/elasticsearch/variables.tf#L162-L165
* `internal_alb.deploy_elb` - decides if elasticsearch module should deploy an ELB or not, while
* `internal_alb.deploy_elb_internal` - controls if the deployed ELB should be really configured as [internal](https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/elb-create-internal-load-balancer.html), which should never be set to `false`, unless ELK is deployed behind VPN, since otherwise that could make Elasticsearch available to the entire world (naturally security groups would have to permit that as well)

**Comment by lehins** [comment]
I guess maybe it was just a bad choice of words `internal`/`external` load balancer, and something like `unsecured`/`secured` load balancer would have been better, but at this point I don't think refactoring would be worth the trouble.
cc @ketzacoatl, could be a possible improvement for the future.
