### ISSUE TITLE
Changelog seem not to be up-to-date

### ISSUE THREAD

**Issue by qrilka** [fpco/terraform-aws-foundation#248]
Release 0.9.4 is out already but the latest released version in CHANGELOG.md is 0.9.3

**Comment by ketzacoatl** [comment]
@JoseD92 maybe you would be able to update that doc to sync?

**Comment by mcgirr** [comment]
I've added a small update to the changelog to add a version `0.9.6` but we still have a good amount of changes that are still in the unreleased section of the changelog that we should sort out. 

It would be good to figure out which of those belong in which release and add entries for `0.9.4` and `0.9.5` as well since those seem to have been skipped when those versions were released.

**Comment by qrilka** [comment]
1d4949ba2c207d0fd209c29b5d009ef9a349e1fe seems to be a fix for this one
