### ISSUE TITLE
example/gitlab: swap ELB for EIP

### ISSUE THREAD

**Issue by ketzacoatl** [fpco/terraform-aws-foundation#61]
in the single-node asg gitlab example, we currently use an ELB. It would be nice to use EIP there instead, and demo that proper setup. An ELB is better for a configuration where we have multiple web workers in the gitlab ASG (and shared data, so no single-node asg). Here is the example env to update: https://github.com/fpco/terraform-aws-foundation/tree/master/examples/gitlab-asg

Given the non-working state of this example, split up into various phases:
- [x]  Get to a state where it's mostly working, documented and as automated as possible
- [x] A persistent EBS volume is mounted to the instance and all gitlab data is stored on that volume - data is retained when the node is replaced
- [ ] Add SMTP server for password notifications
- [ ] Instead of an ELB we use a fixed IP (original task)

**Comment by ketzacoatl** [comment]
This is a good task to get acquainted with Terraform on AWS and the workflows that we are using.

**Comment by AronT-TLV** [comment]
If I understand correctly, the purpose of a single node ASG is to always guarantee there is one node "alive". However to make sure your DNS works if the single node fails and automatically gets replaced, you still need the ELB, so you can CNAME to that which doesn't go away. And AFAIK you still can't use EIP with ELB. I checked as much as I can and even with the new application load balancers, it seems it's still CNAME based--unless I am missing something.

So it seems the only way to use EIP is with a single EC2 instance where you don't care if it goes down. Is that really an important use case? (This is why Kubernetes is so nice).

In any case, if it is useful, is it ok if I rephrase this task to: "create an *additional* example with a gitlab on a single EC2 instance with an EIP attached"? Because I think the current example is still useful.

**Comment by ketzacoatl** [comment]
In the "single node asg" pattern, we define an auto scaling group, but limit it to 1 node. The 1 node can then have a few special resources associated with it, like an EBS volume, or an EIP. If the node is lost, a new one comes up in its place. Recovery is relatively quick, and can be automated in a variety of ways. This workflow also plays well for various upgrade/maintenance/migration scenarios. When the ASG's node comes online, it has the init code it needs to "mount" those "special resources", attaching its EBS volume or EIP. This pattern is used quite widely, as it makes for a great way to host services like gitlab (with a bunch of data), and it also provides the foundation for a "leader" or "controller" role within a cluster (like in kubernetes, controllers deployed by kops are using the Single-Node ASG pattern).

You have a good point about having separate examples for EIP versus ELB, and it's good to evaluate in situations like this. In this case, I think the original plan will be better and that we should stick with it for now. There are a few reasons. The ELB example is more of an entry-level setup, and the EIP is quite a bit more complicated. There are plenty of examples with ELB, and we will likely have others in the future. We will also (likely) be creating other example env for gitlab (with more advanced scaling/HA).

Thanks for reviewing and confirming, I think you have the right idea. One helpful hint: you will want to look at how the EBS volumes are mounted on boot, as the EIP would need something similar during the node's init. This requires a few things, let me know if you have any questions or run into a snag. This is pretty straight-forward, but not as simple as it appears on the outside.

**Comment by AronT-TLV** [comment]
Interesting! The missing piece of information for me is that the new EC2 can attach to a specific, existing EIB. I didn’t know this is an option. Since it is, I understand why you want this as an example over the ELB. I'll start playing with it manually, and after I figure it out, modify the code :) I’ll let you know when I run into issues.

**Comment by ketzacoatl** [comment]
> The missing piece of information for me is that the new EC2 can attach to a specific, existing EIB. 
Right, the Terraform will create an EIP and an ASG/LC with a bunch of init/provisioning shell code as `user_data`. In that `user_data` we tell the instance a specific EBS/EIP it should "attach" during init. We have code to retry the attachment until it is present (but that's easier with a block device..). Also, the instance needs permission to be able to attach the EBS/EIP, and rather than give it access to all EBS/EIP, it only has access to the one that it is associated with.

**Comment by ketzacoatl** [comment]
Let's wrap this up in the week ahead.

**Comment by AronT-TLV** [comment]
Suggestions for EBS:
* create and mount the volume using Make commands
* stop gitlab 
* rsync the existing /gitlab data to the new volume
* restart gitlab

Run this step before initial setup

**Comment by AronT-TLV** [comment]
Suggestions for SMTP:
set up SES as an SMTP server.  This gist shows an example that fits into the gitlab-asg framework): https://gist.github.com/borsboom/3bf05c88c53b19645ac76d6a598a4b70

**Comment by AronT-TLV** [comment]
@borsboom while the sample code you shared works great, getting rid of the ELB (which is the whole point of the exercise) raises the issue of where to put the SSL certificate. The underlying module is opinionated on this so not easily avoided. Investigating various options.

**Comment by ketzacoatl** [comment]
ELB swapped for EIP. Gitlab now also supports Let's Encrypt, so dropped TLS in the process. This is good to resolve, new tickets will be created for additional tasks.
